name: Run Telegram Bot

on:
  push:
    branches: [ "main" ]  # Se activa al hacer push a "main"
  workflow_dispatch:      # Permite ejecutarlo manualmente desde GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest  # Sistema operativo del runner

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Instalar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install telethon

      # 4. Ejecutar el bot (usa screen o nohup para mantenerlo activo)
      - name: Run the bot
        run: |
          screen -dmS bot python -m GPBot  # Usa screen para ejecutar en segundo plano
          sleep 10  # Espera para ver logs (opcional)
          screen -ls  # Verifica que se esté ejecutando